### ISSUE TITLE
New browser instance

### ISSUE THREAD

**Issue by One1Tick** [tarikjaber/Bulk-URL-Opener#1]
Hi and thanks for your work. Could be worth to add a flag to set if the new tabs should be open in the current browser or in a new browser instance (ie new window).
Thanks again.

**Comment by tarikjaber** [comment]
Do you mean for the github icon link in the top right corner? 

![image](https://github.com/tarikjaber/Bulk-URL-Opener/assets/55803936/462774de-943d-4d34-95f6-644892ed605c)

I could add a toggle in the navbar or make a settings page. If there is anything else that would be useful for you just let me know!

**Comment by tarikjaber** [comment]
I am going to implement this for Chrome, Edge, and Firefox. I'll keep you updated.

**Comment by One1Tick** [comment]
Excellent, thanks. Well appreciated.

**Comment by tarikjaber** [comment]
I have added the commit to add this (should be updated soon). Let me know if it works for you. 

This is how the UI will look:
![image](https://github.com/tarikjaber/Bulk-URL-Opener/assets/55803936/ce116f74-59b9-42ce-aa18-ef1238d86d7e)

**Comment by One1Tick** [comment]
Thanks, it works like a charm. Best
